### ISSUE TITLE
Not really an issue!

### ISSUE THREAD

**Issue by Alchunbor** [ArsxnUses/BMI-Calculator#1]
Just wanted to say wow, this code is amazing. I really wonder what else you might have in store for us!
![image2](https://github.com/ArsxnUses/BMI-Calculator/assets/160564466/e14af4aa-db1e-4a68-93c2-a30d6ee6fdb1)

**Comment by TrexSlayer-0** [comment]
Very cool picture Alchunbor i wonder if there is anything special with it

**Comment by ArsxnUses** [comment]
Hints:
`KDhNYlI0IilZZEw2NztDVm88Y0BKXixTQ2pUNyJsTjdSUXcoYTZXJEdySXs+V0NaUm4hZVpbaEhCNklBLjhNYlJ4QQ==`
`V3plWltoUEI3MSwoOE1iUjQiKVlkTDY3ZVpdaDxjQEpeLFNDRFQ2IipOZUxod2RFeWlGQjl5LChPQ2VTNCJPQzdSUXdkRU4=`
